### ISSUE TITLE
Fails during training

### ISSUE THREAD

**Issue by Moktarino** [ghanashyamvtatti/PokeGAN#6]
`Traceback (most recent call last):
  File "./GAN.py", line 303, in <module>
    main()
  File "./GAN.py", line 299, in main
    gan.train_model()
  File "./GAN.py", line 221, in train_model
    generated_images = generator.predict(noise)
  File "/home/daddy/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/daddy/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 723, in predict
    callbacks=callbacks)
  File "/home/daddy/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 411, in model_iteration
    aggregator.finalize()
  File "/home/daddy/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 347, in finalize
    self.results = nest.pack_sequence_as(self._structure, self.results)
  File "/home/daddy/.local/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 457, in pack_sequence_as
    % len(flat_sequence))
ValueError: Structure is a scalar but len(flat_sequence) == 0 > 1
`

**Comment by Moktarino** [comment]
Was user error. Image data path should be "./data" with images stored like "/data/images/${name}.jpg", as indicated by the line "Found 0 images belonging to 0 classes." which wasn't included in the initial report.

Error is caused by empty list reaching generator.predict(noise), as noise's shape is derived from the first image, which in this case is some sort of null.
